=== MobilityData/gbfs-json-schema/v3.1-RC3/gbfs_versions.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://github.com/MobilityData/gbfs-json-schema/blob/master/v3.1-RC3/gbfs_versions.json",
  "description": "Lists all feed endpoints published according to version sof the GBFS documentation. (added in v1.1)",
  "type": "object",
  "properties": {
    "last_updated": {
      "description": "Last time the data in the feed was updated in RFC3339 format.",
      "type": "string",
      "format": "date-time"
    },
    "ttl": {
      "description": "Number of seconds before the data in the feed will be updated again (0 if the data should always be refreshed).",
      "type": "integer",
      "minimum": 0
    },
    "version": {
      "description": "GBFS version number to which the feed conforms, according to the versioning framework.",
      "type": "string",
      "const": "3.1-RC3"
    },
    "data": {
      "description": "Response data in the form of name:value pairs.",
      "type": "object",
      "properties": {
        "versions": {
          "description": "Contains one object, as defined below, for each of the available versions of a feed. The array must be sorted by increasing MAJOR and MINOR version number.",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "version": {
                "description": "The semantic version of the feed in the form X.Y",
                "type": "string",
                "enum": [
                  "1.0",
                  "1.1",
                  "2.0",
                  "2.1",
                  "2.2",
                  "2.3",
                  "3.0",
                  "3.1-RC3"
                ]
              },
              "url": {
                "description": "URL of the corresponding gbfs.json endpoint",
                "type": "string",
                "format": "uri"
              }
            },
            "required": ["version", "url"]
          }
        }
      },
      "required": ["versions"],
      "additionalProperties": false
    }
  },
  "required": ["last_updated", "ttl", "version", "data"]
}

=== MobilityData/gbfs-json-schema/testFixtures/v3.1-RC3/gbfs_versions.json
{
    "last_updated": "2023-07-17T13:34:13+02:00",
    "ttl": 0,
    "version": "3.1-RC3",
    "data": {
      "versions": [
        {
          "version": "2.0",
          "url": "https://www.example.com/gbfs/2/gbfs"
        },
        {
          "version": "3.1-RC3",
          "url": "https://www.example.com/gbfs/3.1-RC3/gbfs"
        }
      ]
    }
  }
