=== MobilityData/gbfs-json-schema/v3.1-RC3/gbfs.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://github.com/MobilityData/gbfs-json-schema/blob/master/v3.1-RC3/gbfs.json",
  "description": "Auto-discovery file that links to all of the other files published by the system.",
  "type": "object",
  "properties": {
    "last_updated": {
      "description": "Last time the data in the feed was updated in RFC3339 format.",
      "type": "string",
      "format": "date-time"
    },
    "ttl": {
      "description": "Number of seconds before the data in the feed will be updated again (0 if the data should always be refreshed).",
      "type": "integer",
      "minimum": 0
    },
    "version": {
      "description": "GBFS version number to which the feed conforms, according to the versioning framework (added in v1.1).",
      "type": "string",
      "const": "3.1-RC3"
    },
    "data": {
      "type": "object",
      "properties": {
        "feeds": {
          "description": "An array of all of the feeds that are published by the auto-discovery file. Each element in the array is an object with the keys below.",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "description": "Key identifying the type of feed this is. The key must be the base file name defined in the spec for the corresponding feed type.",
                "type": "string",
                "enum": [
                  "gbfs",
                  "gbfs_versions",
                  "system_information",
                  "vehicle_types",
                  "station_information",
                  "station_status",
                  "vehicle_status",
                  "system_alerts",
                  "system_regions",
                  "vehicle_availability",
                  "system_pricing_plans",
                  "geofencing_zones"
                ]
              },
              "url": {
                "description": "URL for the feed.",
                "type": "string",
                "format": "uri"
              }
            },
            "required": ["name", "url"]
          },
          "minItems": 1,
          "contains": {
            "properties": {
              "name": { "const": "system_information" }
            }
          }
        }
      },
      "required": ["feeds"]
    }
  },
  "additionalProperties": false,
  "required": ["last_updated", "ttl", "version", "data"]
}

=== MobilityData/gbfs-json-schema/testFixtures/v3.1-RC3/gbfs.json
{
    "last_updated": "2023-07-17T13:34:13+02:00",
    "ttl": 0,
    "version": "3.1-RC3",
    "data": {
      "feeds": [
        {
          "name": "system_information",
          "url": "https://www.example.com/gbfs/1/system_information"
        },
        {
          "name": "station_information",
          "url": "https://www.example.com/gbfs/1/station_information"
        }
      ]
    }
  }
