=== MobilityData/gbfs-json-schema/v3.1-RC3/system_alerts.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://github.com/MobilityData/gbfs-json-schema/blob/master/v3.1-RC3/system_alerts.json",
  "description": "Describes ad-hoc changes to the system.",
  "type": "object",
  "properties": {
    "last_updated": {
      "description":
        "Last time the data in the feed was updated in RFC3339 format.",
      "type": "string",
      "format": "date-time"
    },
    "ttl": {
      "description":
        "Number of seconds before the data in the feed will be updated again (0 if the data should always be refreshed).",
      "type": "integer",
      "minimum": 0
    },
    "version": {
      "description":
        "GBFS version number to which the feed conforms, according to the versioning framework (added in v1.1).",
      "type": "string",
      "const": "3.1-RC3"
    },
    "data": {
      "description": "Array that contains ad-hoc alerts for the system.",
      "type": "object",
      "properties": {
        "alerts": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "alert_id": {
                "description": "Identifier for this alert.",
                "type": "string"
              },
              "type": {
                "description": "Type of alert.",
                "type": "string",
                "enum": [
                  "system_closure",
                  "station_closure",
                  "station_move",
                  "other"
                ]
              },
              "times": {
                "description":
                  "Array of objects indicating when the alert is in effect.",
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "start": {
                      "description": "Start time of the alert.",
                      "type": "string",
                      "format": "date-time"
                    },
                    "end": {
                      "description": "End time of the alert.",
                      "type": "string",
                      "format": "date-time"
                    }
                  }
                },
                "additionalItems": false,
                "required": ["start"]
              },
              "station_ids": {
                "description":
                  "Array of identifiers of the stations for which this alert applies.",
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "region_ids": {
                "description":
                  "Array of identifiers of the regions for which this alert applies.",
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "url": {
                "description":
                  "URL where the customer can learn more information about this alert.",
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "text": {
                      "description": "The translated text.",
                      "type": "string",
                      "format": "uri"
                    },
                    "language": {
                      "description": "IETF BCP 47 language code.",
                      "type": "string",
                      "pattern": "^[a-z]{2,3}(-[A-Z]{2})?$"
                    }
                  },
                  "required": ["text", "language"]
                }
              },
              "summary": {
                "description":
                  "A short summary of this alert to be displayed to the customer.",
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "text": {
                      "description": "The translated text.",
                      "type": "string"
                    },
                    "language": {
                      "description": "IETF BCP 47 language code.",
                      "type": "string",
                      "pattern": "^[a-z]{2,3}(-[A-Z]{2})?$"
                    }
                  },
                  "required": ["text", "language"]
                }
              },
              "description": {
                "description": "Detailed description of the alert.",
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "text": {
                      "description": "The translated text.",
                      "type": "string"
                    },
                    "language": {
                      "description": "IETF BCP 47 language code.",
                      "type": "string",
                      "pattern": "^[a-z]{2,3}(-[A-Z]{2})?$"
                    }
                  },
                  "required": ["text", "language"]
                }
              },
              "last_updated": {
                "description":
                  "Indicates the last time the info for the alert was updated.",
                "type": "string",
                "format": "date-time"
              }
            },
            "required": ["alert_id", "type", "summary"]
          }
        }
      },
      "required": ["alerts"]
    }
  },
  "required": ["last_updated", "ttl", "version", "data"]
}

=== MobilityData/gbfs-json-schema/testFixtures/v3.1-RC3/system_alerts.json
{
    "last_updated": "2023-07-17T13:34:13+02:00",
    "ttl": 60,
    "version": "3.1-RC3",
    "data": {
      "alerts": [
        {
          "alert_id": "21",
          "type": "station_closure",
          "station_ids": [
            "123",
            "456",
            "789"
          ],
          "times": [
            {
              "start": "2023-07-17T13:34:13+02:00",
              "end": "2023-07-18T13:34:13+02:00"
            }
          ],
          "url": [
            {
              "text": "https://example.com/more-info",
              "language": "en"
            }
          ], 
          "summary": [
            {
              "text": "Disruption of Service",
              "language": "en"
            }
          ],
          "description": [
            {
              "text": "The three stations on Broadway will be out of service from 12:00am Nov 3 to 3:00pm Nov 6th to accommodate road work",
              "language": "en"
            }
          ],
          "last_updated": "2023-07-17T13:34:13+02:00"
        }
      ]
    }
  }
