=== MobilityData/gbfs-json-schema/v3.1-RC3/system_pricing_plans.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id":
    "https://github.com/MobilityData/gbfs-json-schema/blob/master/v3.1-RC3/system_pricing_plans.json",
  "description": "Describes the pricing schemes of the system.",
  "type": "object",
  "properties": {
    "last_updated": {
      "description":
        "Last time the data in the feed was updated in RFC3339 format.",
      "type": "string",
      "format": "date-time"
    },
    "ttl": {
      "description":
        "Number of seconds before the data in the feed will be updated again (0 if the data should always be refreshed).",
      "type": "integer",
      "minimum": 0
    },
    "version": {
      "description":
        "GBFS version number to which the feed conforms, according to the versioning framework (added in v1.1).",
      "type": "string",
      "const": "3.1-RC3"
    },
    "data": {
      "description":
        "Array that contains one object per plan as defined below.",
      "type": "object",
      "properties": {
        "plans": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "plan_id": {
                "description": "Identifier of a pricing plan in the system.",
                "type": "string"
              },
              "url": {
                "description":
                  "URL where the customer can learn more about this pricing plan.",
                "type": "string",
                "format": "uri"
              },
              "name": {
                "description": "Name of this pricing plan.",
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "text": {
                      "description": "The translated text.",
                      "type": "string"
                    },
                    "language": {
                      "description": "IETF BCP 47 language code.",
                      "type": "string",
                      "pattern": "^[a-z]{2,3}(-[A-Z]{2})?$"
                    }
                  },
                  "required": ["text", "language"]
                }
              },
              "currency": {
                "description":
                  "Currency used to pay the fare in ISO 4217 code.",
                "type": "string",
                "pattern": "^\\w{3}$"
              },
              "price": {
                "description": "Fare price.",
                "type": "number",
                "minimum": 0
              },
              "reservation_price_per_min": {
                "description": "The cost, described as per minute rate, to reserve the vehicle prior to beginning a rental.",
                "type": "number",
                "minimum": 0
              },
              "reservation_price_flat_rate": {
                "description": "The cost, described as a flat rate, to reserve the vehicle prior to beginning a rental.",
                "type": "number",
                "minimum": 0
              },
              "is_taxable": {
                "description":
                  "Will additional tax be added to the base price?",
                "type": "boolean"
              },
              "description": {
                "description":
                  "Customer-readable description of the pricing plan.",
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "text": {
                      "description": "The translated text.",
                      "type": "string"
                    },
                    "language": {
                      "description": "IETF BCP 47 language code.",
                      "type": "string",
                      "pattern": "^[a-z]{2,3}(-[A-Z]{2})?$"
                    }
                  },
                  "required": ["text", "language"]
                }
              },
              "per_km_pricing": {
                "description":
                  "Array of segments when the price is a function of distance travelled, displayed in kilometers (added in v2.1-RC2).",
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "start": {
                      "description":
                        "Number of kilometers that have to elapse before this segment starts applying (added in v2.1-RC2).",
                      "type": "integer",
                      "minimum": 0
                    },
                    "rate": {
                      "description":
                        "Rate that is charged for each kilometer interval after the start (added in v2.1-RC2).",
                      "type": "number"
                    },
                    "interval": {
                      "description":
                        "Interval in kilometers at which the rate of this segment is either reapplied indefinitely, or if defined, up until (but not including) end kilometer (added in v2.1-RC2).",
                      "type": "integer",
                      "minimum": 0
                    },
                    "end": {
                      "description":
                        "The kilometer at which the rate will no longer apply (added in v2.1-RC2).",
                      "type": "integer",
                      "minimum": 0
                    }
                  },
                  "required": ["start", "rate", "interval"]
                }
              },
              "per_min_pricing": {
                "description":
                  "Array of segments when the price is a function of time travelled, displayed in minutes (added in v2.1-RC2).",
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "start": {
                      "description":
                        "Number of minutes that have to elapse before this segment starts applying (added in v2.1-RC2).",
                      "type": "integer",
                      "minimum": 0
                    },
                    "rate": {
                      "description":
                        "Rate that is charged for each minute interval after the start (added in v2.1-RC2).",
                      "type": "number"
                    },
                    "interval": {
                      "description":
                        "Interval in minutes at which the rate of this segment is either reapplied (added in v2.1-RC2).",
                      "type": "integer",
                      "minimum": 0
                    },
                    "end": {
                      "description":
                        "The minute at which the rate will no longer apply (added in v2.1-RC2).",
                      "type": "integer",
                      "minimum": 0
                    }
                  },
                  "required": ["start", "rate", "interval"]
                }
              },
              "surge_pricing": {
                "description":
                  "Is there currently an increase in price in response to increased demand in this pricing plan? (added in v2.1-RC2)",
                "type": "boolean"
              },
              "fare_capping": {
                "type": "object",
                "description": "Object defining a capped fare once a price threshold has been spent within a timeframe. (added in v3.1-RC3)",
                "properties": {
                  "duration": {
                    "description": "Amount of time in minutes during which the fare is capped.",
                    "type": "integer",
                    "minimum": 0
                  },
                  "price": {
                    "description": "The maximum fare threshold for the current timeframe, in the unit specified by currency",
                    "type": "number",
                    "minimum": 0
                  }
                },
                "required": ["duration", "price"]
              }
            },
            "required": [
              "plan_id",
              "name",
              "currency",
              "price",
              "is_taxable",
              "description"
            ],
            "dependencies": {
              "reservation_price_flat_rate": { "not": { "required": ["reservation_price_per_min"] } },
              "reservation_price_per_min": { "not": { "required": ["reservation_price_flat_rate"] } }
            }
          }
        }
      },
      "required": ["plans"]
    }
  },
  "required": ["last_updated", "ttl", "version", "data"]
}

=== MobilityData/gbfs-json-schema/testFixtures/v3.1-RC3/system_pricing_plans.json
{
    "last_updated": "2023-07-17T13:34:13+02:00",
    "ttl": 0,
    "version": "3.1-RC3",
    "data": {
      "plans": [
        {
          "plan_id": "plan2",
          "name": [
            {
              "text": "One-Way",
              "language": "en"
            }
          ],
          "currency": "USD",
          "price": 2.00,
          "reservation_price_per_min": 0.15,
          "is_taxable": false,
          "description": [
            {
              "text": "Includes 10km, overage fees apply after 10km.",
              "language": "en"
            }
          ],
          "per_km_pricing": [
            {
              "start": 10,
              "rate": 1.00,
              "interval": 1,
              "end": 25
            },
            {
              "start": 25,
              "rate": 0.50,
              "interval": 1
            },
            {
              "start": 25,
              "rate": 3.00,
              "interval": 5
            }
          ]
        }
      ]
    }
  }
