=== MobilityData/gbfs-json-schema/v3.1-RC3/system_regions.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://github.com/MobilityData/gbfs-json-schema/blob/master/v3.1-RC3/system_regions.json",
  "description":
    "Describes regions for a system that is broken up by geographic or political region.",
  "type": "object",
  "properties": {
    "last_updated": {
      "description":
        "Last time the data in the feed was updated in RFC3339 format.",
      "type": "string",
      "format": "date-time"
    },
    "ttl": {
      "description":
        "Number of seconds before the data in the feed will be updated again (0 if the data should always be refreshed).",
      "type": "integer",
      "minimum": 0
    },
    "version": {
      "description":
        "GBFS version number to which the feed conforms, according to the versioning framework (added in v1.1).",
      "type": "string",
      "const": "3.1-RC3"
    },
    "data": {
      "description": "Describe regions for a system that is broken up by geographic or political region.",
      "type": "object",
      "properties": {
        "regions": {
          "description": "Array of regions.",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "region_id": {
                "description": "identifier of the region.",
                "type": "string"
              },
              "name": {
                "description": "Public name for this region.",
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "text": {
                      "description": "The translated text.",
                      "type": "string"
                    },
                    "language": {
                      "description": "IETF BCP 47 language code.",
                      "type": "string",
                      "pattern": "^[a-z]{2,3}(-[A-Z]{2})?$"
                    }
                  },
                  "required": ["text", "language"]
                }
              }
            },
            "required": ["region_id", "name"]
          }
        }
      },
      "required": ["regions"]
    }
  },
  "required": ["last_updated", "ttl", "version", "data"]
}

=== MobilityData/gbfs-json-schema/testFixtures/v3.1-RC3/system_regions.json
{
    "last_updated": "2023-07-17T13:34:13+02:00",
    "ttl": 86400,
    "version": "3.1-RC3",
    "data": {
      "regions": [
        {
          "name": [
            {
              "text": "North",
              "language": "en"
            }
          ],
          "region_id": "3"
        },
        {
          "name": [
            {
              "text": "East",
              "language": "en"
            }
          ],
          "region_id": "4"
        },
        {
          "name": [
            {
              "text": "South",
              "language": "en"
            }
          ],
          "region_id": "5"
        },
        {
          "name": [
            {
              "text": "West",
              "language": "en"
            }
          ],
          "region_id": "6"
        }
      ]
    }
  }
