=== MobilityData/gbfs-json-schema/v3.1-RC3/vehicle_availability.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/MobilityData/gbfs-json-schema/blob/master/v3.1-RC3/vehicle_availability.json",
  "description": "Describes the vehicle availabilities of the system.",
  "type": "object",
  "properties": {
    "last_updated": {
      "description": "Last time the data in the feed was updated in RFC3339 format.",
      "type": "string",
      "format": "date-time"
    },
    "ttl": {
      "description": "Number of seconds before the data in the feed will be updated again (0 if the data should always be refreshed).",
      "type": "integer",
      "minimum": 0
    },
    "version": {
      "description": "GBFS version number to which the feed conforms, according to the versioning framework (added in v1.1).",
      "type": "string",
      "const": "3.1-RC3"
    },
    "data": {
      "type": "object",
      "properties": {
        "vehicles": {
          "type": "array",
          "description": "Contains one object per vehicle.",
          "items": {
            "type": "object",
            "properties": {
              "vehicle_id": {
                "type": "string",
                "description": "Identifier of a vehicle"
              },
              "vehicle_type_id": {
                "type": "string",
                "description": "Unique identifier of a vehicle type as defined in vehicle_types.json"
              },
              "station_id": {
                "type": "string",
                "description": " The id of the station where this vehicle is located when available"
              },
              "pricing_plan_id": {
                "type": "string",
                "description": "The plan_id of the pricing plan this vehicle is eligible for"
              },
              "vehicle_equipment": {
                "type": "array",
                "description": "List of vehicle equipment provided by the operator",
                "items": {
                  "type": "string"
                }
              },
              "availabilities": {
                "type": "array",
                "description": "Array of time slots during which the specified vehicle is available.",
                "items": {
                  "type": "object",
                  "properties": {
                    "from": {
                      "type": "string",
                      "description": "Start date and time of available time slot.",
                      "format": "date-time"
                    },
                    "until": {
                      "type": "string",
                      "description": "End date and time of available time slot.",
                      "format": "date-time"
                    }
                  },
                  "required": ["from"],
                  "additionalProperties": false
                }
              }
            },
            "required": [
              "vehicle_id",
              "station_id",
              "availabilities"
            ],
            "additionalProperties": false
          }
        }
      },
      "required": ["vehicles"],
      "additionalProperties": false
    }
  },
  "required": ["last_updated", "ttl", "version", "data"],
  "additionalProperties": false
}

=== MobilityData/gbfs-json-schema/testFixtures/v3.1-RC3/vehicle_availability.json
{
  "last_updated": "2025-07-17T13:34:13+02:00",
  "ttl": 0,
  "version": "3.1-RC3",
  "data": {
    "vehicles": [
      {
        "vehicle_id": "vehicle_id_1",
        "vehicle_type_id": "abc123",
        "station_id": "pga",
        "pricing_plan_id": "plan2",
        "vehicle_equipment": [
          "child_seat_a"
        ],
        "availabilities": [
          {
            "from": "2025-05-24T00:00:00+02:00",
            "until": "2025-07-24T23:59:00+02:00"
          },
          {
            "from": "2025-10-25T00:00:00+02:00"
          }
        ]
      }
    ]
  }
}
