=== MobilityData/gbfs-json-schema/v2.3/gbfs.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://github.com/NABSA/gbfs/blob/v2.3/gbfs.md#gbfsjson",
  "description":
    "Auto-discovery file that links to all of the other files published by the system.",
  "type": "object",
  "properties": {
    "last_updated": {
      "description":
        "Last time the data in the feed was updated in POSIX time.",
      "type": "integer",
      "minimum": 1450155600
    },
    "ttl": {
      "description":
        "Number of seconds before the data in the feed will be updated again (0 if the data should always be refreshed).",
      "type": "integer",
      "minimum": 0
    },
    "version": {
      "description":
        "GBFS version number to which the feed conforms, according to the versioning framework (added in v1.1).",
      "type": "string",
      "const": "2.3"
    },
    "data": {
      "description": "Response data in the form of name:value pairs.",
      "type": "object",
      "patternProperties": {
        "^[a-z]{2,3}(-[A-Z]{2})?$": {
          "type": "object",
          "properties": {
            "feeds": {
              "description":
                "An array of all of the feeds that are published by the auto-discovery file. Each element in the array is an object with the keys below.",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "description":
                      "Key identifying the type of feed this is. The key must be the base file name defined in the spec for the corresponding feed type.",
                    "type": "string",
                    "enum": [
                      "gbfs",
                      "gbfs_versions",
                      "system_information",
                      "vehicle_types",
                      "station_information",
                      "station_status",
                      "free_bike_status",
                      "system_hours",
                      "system_alerts",
                      "system_calendar",
                      "system_regions",
                      "system_pricing_plans",
                      "geofencing_zones"
                    ]
                  },
                  "url": {
                    "description": "URL for the feed.",
                    "type": "string",
                    "format": "uri"
                  }
                },
                "required": ["name", "url"]
              }
            },
            "required": true
          }
        },
        "required": true
      },
      "additionalProperties": false
    }
  },
  "required": ["last_updated", "ttl", "version", "data"]
}

=== MobilityData/gbfs-json-schema/testFixtures/v2.3/station_information_virtual_station.json
{
  "last_updated": 1640887163,
  "ttl": 0,
  "version": "2.3",
  "data": {
    "stations": [
      {
        "station_id": "station12",
        "name": "SE Belmont & SE 10 th",
        "lat": 45.516445,
        "lon": -122.655775,
        "is_valet_station": false,
        "is_virtual_station": true,
        "is_charging_station": false,
        "station_area": {
          "type": "MultiPolygon",
          "coordinates": [
            [
              [
                [
                  -122.655775,
                  45.516445
                ],
                [
                  -122.655705,
                  45.516445
                ],
                [
                  -122.655705,
                  45.516495
                ],
                [
                  -122.655775,
                  45.516495
                ],
                [
                  -122.655775,
                  45.516445
                ]
              ]
            ]
          ]
        },
        "capacity": 16,
        "vehicle_capacity": {
          "abc123": 8,
          "def456": 8,
          "ghi789": 16
        }
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/testFixtures/v2.3/system_pricing_plans_a.json
{
  "last_updated": 1640887163,
  "ttl": 0,
  "version": "2.3",
  "data": {
    "plans": [
      {
        "plan_id": "plan2",
        "name": "One-Way",
        "currency": "USD",
        "price": 2.00,
        "is_taxable": false,
        "description": "Includes 10km, overage fees apply after 10km.",
        "per_km_pricing": [
          {
            "start": 10,
            "rate": 1.00,
            "interval": 1,
            "end": 25
          },
          {
            "start": 25,
            "rate": 0.50,
            "interval": 1
          },
          {
            "start": 25,
            "rate": 3.00,
            "interval": 5
          }
        ]
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/testFixtures/v2.3/station_information_physical_station.json
{
  "last_updated": 1640887163,
  "ttl": 0,
  "version": "2.3",
  "data": {
    "stations": [
      {
        "station_id": "pga",
        "name": "Parking garage A",
        "lat": 12.345678,
        "lon": 45.678901,
        "parking_type": "underground_parking",
        "parking_hoop": false,
        "contact_phone": "+33109874321",
        "is_charging_station": true,
        "vehicle_type_capacity": {
          "abc123": 7,
          "def456": 9
        }
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/testFixtures/v2.3/system_hours.json
{
  "last_updated": 1640887163,
  "ttl": 86400,
  "version": "2.3",
  "data": {
    "rental_hours": [
      {
        "user_types": [ "member" ],
        "days": [
          "sat",
          "sun"
        ],
        "start_time": "00:00:00",
        "end_time": "23:59:59"
      },
      {
        "user_types": [ "nonmember" ],
        "days": [
          "sat",
          "sun"
        ],
        "start_time": "05:00:00",
        "end_time": "23:59:59"
      },
      {
        "user_types": [
          "member",
          "nonmember"
        ],
        "days": [
          "mon",
          "tue",
          "wed",
          "thu",
          "fri"
        ],
        "start_time": "00:00:00",
        "end_time": "23:59:59"
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/testFixtures/v2.3/vehicle_types.json
{
  "last_updated": 1606830898,
  "ttl": 300,
  "version": "2.3",
  "data": {
    "vehicle_types": [
      {
        "vehicle_type_id": "TST:VehicleType:Scooter",
        "form_factor": "scooter",
        "propulsion_type": "electric",
        "max_range_meters": 0.0
      },
      {
        "vehicle_type_id": "TST:VehicleType:CityBike",
        "form_factor": "bicycle",
        "propulsion_type": "human"
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/testFixtures/v2.3/geofencing_zones.json
{
  "last_updated": 1640887163,
  "ttl": 60,
  "version": "2.3",
  "data": {
    "geofencing_zones": {
      "type": "FeatureCollection",
      "features": [
        {
          "type": "Feature",
          "geometry": {
            "type": "MultiPolygon",
            "coordinates": [
              [
                [
                  [
                    -122.578067,
                    45.562982
                  ],
                  [
                    -122.661838,
                    45.562741
                  ],
                  [
                    -122.661151,
                    45.504542
                  ],
                  [
                    -122.578926,
                    45.5046625
                  ],
                  [
                    -122.578067,
                    45.562982
                  ]
                ]
              ],
              [
                [
                  [
                    -122.650680,
                    45.548197
                  ],
                  [
                    -122.650852,
                    45.534731
                  ],
                  [
                    -122.630939,
                    45.535212
                  ],
                  [
                    -122.630424,
                    45.548197
                  ],
                  [
                    -122.650680,
                    45.548197
                  ]
                ]
              ]
            ]
          },
          "properties": {
            "name": "NE 24th/NE Knott",
            "start": 1593878400,
            "end": 1593907260,
            "rules": [
              {
                "vehicle_type_id": [
                  "moped1",
                  "car1"
                ],
                "ride_allowed": false,
                "ride_through_allowed": true,
                "maximum_speed_kph": 10,
                "station_parking": true
              }
            ]
          }
        }
      ]
    }
  }
}

=== MobilityData/gbfs-json-schema/testFixtures/v2.3/system_alerts.json
{
  "last_updated": 1751434987,
  "ttl": 0,
  "version": "2.3",
  "data": {
    "alerts": [
      {
        "alert_id": "21",
        "type": "station_closure",
        "station_ids": [
          "123",
          "456",
          "789"
        ],
        "times": [
          {
            "start": 1751437263,
            "end": 1751434987
          }
        ],
        "url": "https://example.com/more-info",
        "summary": "Closed for maintenance",
        "description": "Station is closed to install more docks.",
        "last_updated": 1751434987
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/testFixtures/v2.3/gbfs.json
{
  "last_updated": 1640887163,
  "ttl": 0,
  "version": "2.3",
  "data": {
    "en": {
      "feeds": [
        {
          "name": "system_information",
          "url": "https://www.example.com/gbfs/1/en/system_information"
        },
        {
          "name": "station_information",
          "url": "https://www.example.com/gbfs/1/en/station_information"
        }
      ]
    },
    "fr" : {
      "feeds": [
        {
          "name": "system_information",
          "url": "https://www.example.com/gbfs/1/fr/system_information"
        },
        {
          "name": "station_information",
          "url": "https://www.example.com/gbfs/1/fr/station_information"
        }
      ]
    }
  }
}
