=== MobilityData/gbfs-json-schema/gbfs-java-model/src/main/resources/schema/v2.3/system_information/system_information.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id":
    "https://github.com/NABSA/gbfs/blob/v2.3/gbfs.md#system_informationjson",
  "description":
    "Details including system operator, system location, year implemented, URL, contact info, time zone.",
  "type": "object",
  "properties": {
    "last_updated": {
      "description":
        "Last time the data in the feed was updated in POSIX time.",
      "type": "integer",
      "minimum": 1450155600
    },
    "ttl": {
      "description":
        "Number of seconds before the data in the feed will be updated again (0 if the data should always be refreshed).",
      "type": "integer",
      "minimum": 0
    },
    "version": {
      "description":
        "GBFS version number to which the feed conforms, according to the versioning framework (added in v1.1).",
      "type": "string",
      "const": "2.3"
    },
    "data": {
      "description": "Response data in the form of name:value pairs.",
      "type": "object",
      "properties": {
        "system_id": {
          "description":
            "Identifier for this vehicle share system. This should be globally unique (even between different systems).",
          "type": "string"
        },
        "language": {
          "description":
            "The language that will be used throughout the rest of the files. It must match the value in the gbfs.json file.",
          "type": "string",
          "pattern": "^[a-z]{2,3}(-[A-Z]{2})?$"
        },
        "name": {
          "description": "Name of the system to be displayed to customers.",
          "type": "string"
        },
        "short_name": {
          "description": "Optional abbreviation for a system.",
          "type": "string"
        },
        "operator": {
          "description": "Name of the operator",
          "type": "string"
        },
        "url": {
          "description": "The URL of the vehicle share system.",
          "type": "string",
          "format": "uri"
        },
        "purchase_url": {
          "description": "URL where a customer can purchase a membership.",
          "type": "string",
          "format": "uri"
        },
        "start_date": {
          "description": "Date that the system began operations.",
          "type": "string",
          "format": "date"
        },
        "phone_number": {
          "description":
            "A single voice telephone number for the specified system that presents the telephone number as typical for the system's service area.",
          "type": "string"
        },
        "email": {
          "description":
            "Email address actively monitored by the operator's customer service department.",
          "type": "string",
          "format": "email"
        },
        "feed_contact_email": {
          "description":
            "A single contact email address for consumers of this feed to report technical issues (added in v1.1).",
          "type": "string",
          "format": "email"
        },
        "timezone": {
          "description": "The time zone where the system is located.",
          "type": "string",
          "enum": [
            "Africa/Abidjan",
            "Africa/Algiers",
            "Africa/Bissau",
            "Africa/Cairo",
            "Africa/Casablanca",
            "Africa/Ceuta",
            "Africa/El_Aaiun",
            "Africa/Johannesburg",
            "Africa/Juba",
            "Africa/Khartoum",
            "Africa/Lagos",
            "Africa/Maputo",
            "Africa/Monrovia",
            "Africa/Nairobi",
            "Africa/Ndjamena",
            "Africa/Sao_Tome",
            "Africa/Tripoli",
            "Africa/Tunis",
            "Africa/Windhoek",
            "America/Adak",
            "America/Anchorage",
            "America/Araguaina",
            "America/Argentina/Buenos_Aires",
            "America/Argentina/Catamarca",
            "America/Argentina/Cordoba",
            "America/Argentina/Jujuy",
            "America/Argentina/La_Rioja",
            "America/Argentina/Mendoza",
            "America/Argentina/Rio_Gallegos",
            "America/Argentina/Salta",
            "America/Argentina/San_Juan",
            "America/Argentina/San_Luis",
            "America/Argentina/Tucuman",
            "America/Argentina/Ushuaia",
            "America/Asuncion",
            "America/Bahia",
            "America/Bahia_Banderas",
            "America/Barbados",
            "America/Belem",
            "America/Belize",
            "America/Boa_Vista",
            "America/Bogota",
            "America/Boise",
            "America/Cambridge_Bay",
            "America/Campo_Grande",
            "America/Cancun",
            "America/Caracas",
            "America/Cayenne",
            "America/Chicago",
            "America/Chihuahua",
            "America/Costa_Rica",
            "America/Cuiaba",
            "America/Danmarkshavn",
            "America/Dawson",
            "America/Dawson_Creek",
            "America/Denver",
            "America/Detroit",
            "America/Edmonton",
            "America/Eirunepe",
            "America/El_Salvador",
            "America/Fort_Nelson",
            "America/Fortaleza",
            "America/Glace_Bay",
            "America/Goose_Bay",
            "America/Grand_Turk",
            "America/Guatemala",
            "America/Guayaquil",
            "America/Guyana",
            "America/Halifax",
            "America/Havana",
            "America/Hermosillo",
            "America/Indiana/Indianapolis",
            "America/Indiana/Knox",
            "America/Indiana/Marengo",
            "America/Indiana/Petersburg",
            "America/Indiana/Tell_City",
            "America/Indiana/Vevay",
            "America/Indiana/Vincennes",
            "America/Indiana/Winamac",
            "America/Inuvik",
            "America/Iqaluit",
            "America/Jamaica",
            "America/Juneau",
            "America/Kentucky/Louisville",
            "America/Kentucky/Monticello",
            "America/La_Paz",
            "America/Lima",
            "America/Los_Angeles",
            "America/Maceio",
            "America/Managua",
            "America/Manaus",
            "America/Martinique",
            "America/Matamoros",
            "America/Mazatlan",
            "America/Menominee",
            "America/Merida",
            "America/Metlakatla",
            "America/Mexico_City",
            "America/Miquelon",
            "America/Moncton",
            "America/Monterrey",
            "America/Montevideo",
            "America/New_York",
            "America/Nipigon",
            "America/Nome",
            "America/Noronha",
            "America/North_Dakota/Beulah",
            "America/North_Dakota/Center",
            "America/North_Dakota/New_Salem",
            "America/Nuuk",
            "America/Ojinaga",
            "America/Panama",
            "America/Pangnirtung",
            "America/Paramaribo",
            "America/Phoenix",
            "America/Port-au-Prince",
            "America/Porto_Velho",
            "America/Puerto_Rico",
            "America/Punta_Arenas",
            "America/Rainy_River",
            "America/Rankin_Inlet",
            "America/Recife",
            "America/Regina",
            "America/Resolute",
            "America/Rio_Branco",
            "America/Santarem",
            "America/Santiago",
            "America/Santo_Domingo",
            "America/Sao_Paulo",
            "America/Scoresbysund",
            "America/Sitka",
            "America/St_Johns",
            "America/Swift_Current",
            "America/Tegucigalpa",
            "America/Thule",
            "America/Thunder_Bay",
            "America/Tijuana",
            "America/Toronto",
            "America/Vancouver",
            "America/Whitehorse",
            "America/Winnipeg",
            "America/Yakutat",
            "America/Yellowknife",
            "Antarctica/Casey",
            "Antarctica/Davis",
            "Antarctica/Macquarie",
            "Antarctica/Mawson",
            "Antarctica/Palmer",
            "Antarctica/Rothera",
            "Antarctica/Troll",
            "Antarctica/Vostok",
            "Asia/Almaty",
            "Asia/Amman",
            "Asia/Anadyr",
            "Asia/Aqtau",
            "Asia/Aqtobe",
            "Asia/Ashgabat",
            "Asia/Atyrau",
            "Asia/Baghdad",
            "Asia/Baku",
            "Asia/Bangkok",
            "Asia/Barnaul",
            "Asia/Beirut",
            "Asia/Bishkek",
            "Asia/Brunei",
            "Asia/Chita",
            "Asia/Choibalsan",
            "Asia/Colombo",
            "Asia/Damascus",
            "Asia/Dhaka",
            "Asia/Dili",
            "Asia/Dubai",
            "Asia/Dushanbe",
            "Asia/Famagusta",
            "Asia/Gaza",
            "Asia/Hebron",
            "Asia/Ho_Chi_Minh",
            "Asia/Hong_Kong",
            "Asia/Hovd",
            "Asia/Irkutsk",
            "Asia/Jakarta",
            "Asia/Jayapura",
            "Asia/Jerusalem",
            "Asia/Kabul",
            "Asia/Kamchatka",
            "Asia/Karachi",
            "Asia/Kathmandu",
            "Asia/Khandyga",
            "Asia/Kolkata",
            "Asia/Krasnoyarsk",
            "Asia/Kuala_Lumpur",
            "Asia/Kuching",
            "Asia/Macau",
            "Asia/Magadan",
            "Asia/Makassar",
            "Asia/Manila",
            "Asia/Nicosia",
            "Asia/Novokuznetsk",
            "Asia/Novosibirsk",
            "Asia/Omsk",
            "Asia/Oral",
            "Asia/Pontianak",
            "Asia/Pyongyang",
            "Asia/Qatar",
            "Asia/Qostanay",
            "Asia/Qyzylorda",
            "Asia/Riyadh",
            "Asia/Sakhalin",
            "Asia/Samarkand",
            "Asia/Seoul",
            "Asia/Shanghai",
            "Asia/Singapore",
            "Asia/Srednekolymsk",
            "Asia/Taipei",
            "Asia/Tashkent",
            "Asia/Tbilisi",
            "Asia/Tehran",
            "Asia/Thimphu",
            "Asia/Tokyo",
            "Asia/Tomsk",
            "Asia/Ulaanbaatar",
            "Asia/Urumqi",
            "Asia/Ust-Nera",
            "Asia/Vladivostok",
            "Asia/Yakutsk",
            "Asia/Yangon",
            "Asia/Yekaterinburg",
            "Asia/Yerevan",
            "Atlantic/Azores",
            "Atlantic/Bermuda",
            "Atlantic/Canary",
            "Atlantic/Cape_Verde",
            "Atlantic/Faroe",
            "Atlantic/Madeira",
            "Atlantic/Reykjavik",
            "Atlantic/South_Georgia",
            "Atlantic/Stanley",
            "Australia/Adelaide",
            "Australia/Brisbane",
            "Australia/Broken_Hill",
            "Australia/Darwin",
            "Australia/Eucla",
            "Australia/Hobart",
            "Australia/Lindeman",
            "Australia/Lord_Howe",
            "Australia/Melbourne",
            "Australia/Perth",
            "Australia/Sydney",
            "CET",
            "CST6CDT",
            "EET",
            "EST",
            "EST5EDT",
            "Etc/GMT",
            "Etc/GMT-1",
            "Etc/GMT-10",
            "Etc/GMT-11",
            "Etc/GMT-12",
            "Etc/GMT-13",
            "Etc/GMT-14",
            "Etc/GMT-2",
            "Etc/GMT-3",
            "Etc/GMT-4",
            "Etc/GMT-5",
            "Etc/GMT-6",
            "Etc/GMT-7",
            "Etc/GMT-8",
            "Etc/GMT-9",
            "Etc/GMT+1",
            "Etc/GMT+10",
            "Etc/GMT+11",
            "Etc/GMT+12",
            "Etc/GMT+2",
            "Etc/GMT+3",
            "Etc/GMT+4",
            "Etc/GMT+5",
            "Etc/GMT+6",
            "Etc/GMT+7",
            "Etc/GMT+8",
            "Etc/GMT+9",
            "Etc/UTC",
            "Europe/Amsterdam",
            "Europe/Andorra",
            "Europe/Astrakhan",
            "Europe/Athens",
            "Europe/Belgrade",
            "Europe/Berlin",
            "Europe/Brussels",
            "Europe/Bucharest",
            "Europe/Budapest",
            "Europe/Chisinau",
            "Europe/Copenhagen",
            "Europe/Dublin",
            "Europe/Gibraltar",
            "Europe/Helsinki",
            "Europe/Istanbul",
            "Europe/Kaliningrad",
            "Europe/Kiev",
            "Europe/Kirov",
            "Europe/Lisbon",
            "Europe/London",
            "Europe/Luxembourg",
            "Europe/Madrid",
            "Europe/Malta",
            "Europe/Minsk",
            "Europe/Monaco",
            "Europe/Moscow",
            "Europe/Oslo",
            "Europe/Paris",
            "Europe/Prague",
            "Europe/Riga",
            "Europe/Rome",
            "Europe/Samara",
            "Europe/Saratov",
            "Europe/Simferopol",
            "Europe/Sofia",
            "Europe/Stockholm",
            "Europe/Tallinn",
            "Europe/Tirane",
            "Europe/Ulyanovsk",
            "Europe/Uzhgorod",
            "Europe/Vienna",
            "Europe/Vilnius",
            "Europe/Volgograd",
            "Europe/Warsaw",
            "Europe/Zaporozhye",
            "Europe/Zurich",
            "HST",
            "Indian/Chagos",
            "Indian/Christmas",
            "Indian/Cocos",
            "Indian/Kerguelen",
            "Indian/Mahe",
            "Indian/Maldives",
            "Indian/Mauritius",
            "Indian/Reunion",
            "MET",
            "MST",
            "MST7MDT",
            "Pacific/Apia",
            "Pacific/Auckland",
            "Pacific/Bougainville",
            "Pacific/Chatham",
            "Pacific/Chuuk",
            "Pacific/Easter",
            "Pacific/Efate",
            "Pacific/Fakaofo",
            "Pacific/Fiji",
            "Pacific/Funafuti",
            "Pacific/Galapagos",
            "Pacific/Gambier",
            "Pacific/Guadalcanal",
            "Pacific/Guam",
            "Pacific/Honolulu",
            "Pacific/Kanton",
            "Pacific/Kiritimati",
            "Pacific/Kosrae",
            "Pacific/Kwajalein",
            "Pacific/Majuro",
            "Pacific/Marquesas",
            "Pacific/Nauru",
            "Pacific/Niue",
            "Pacific/Norfolk",
            "Pacific/Noumea",
            "Pacific/Pago_Pago",
            "Pacific/Palau",
            "Pacific/Pitcairn",
            "Pacific/Pohnpei",
            "Pacific/Port_Moresby",
            "Pacific/Rarotonga",
            "Pacific/Tahiti",
            "Pacific/Tarawa",
            "Pacific/Tongatapu",
            "Pacific/Wake",
            "Pacific/Wallis",
            "PST8PDT",
            "WET"
          ]
        },
        "license_url": {
          "description":
            "A fully qualified URL of a page that defines the license terms for the GBFS data for this system.",
          "type": "string",
          "format": "uri"
        },
        "brand_assets": {
          "description":
          "An object where each key defines one of the items listed below (added in v2.3-RC).",
          "type": "object",
          "properties": {
            "brand_last_modified": {
              "description": "Date that indicates the last time any included brand assets were updated (added in v2.3-RC).",
              "type": "string",
              "format": "date"
            },
            "brand_terms_url": {
              "description": "A fully qualified URL pointing to the location of a page that defines the license terms of brand icons, colors or other trademark information (added in v2.3-RC).",
              "type": "string",
              "format": "uri"
            },
            "brand_image_url": {
              "description": "A fully qualified URL pointing to the location of a graphic file representing the brand for the service (added in v2.3-RC). ",
              "type": "string",
              "format": "uri"
            },
            "brand_image_url_dark": {
              "description": "A fully qualified URL pointing to the location of a graphic file representing the brand for the service for use in dark mode (added in v2.3-RC).",
              "type": "string",
              "format": "uri"
            },
            "color": {
              "description": "Color used to represent the brand for the service (added in v2.3-RC)",
              "type": "string",
              "pattern": "^#([a-fA-F0-9]{6})$"
            }
          },
          "required": ["brand_last_modified", "brand_image_url"]
        },
        "terms_url": {
          "description":
          "A fully qualified URL pointing to the terms of service (added in v2.3-RC)",
          "type": "string",
          "format": "uri"
        },
        "terms_last_updated": {
          "description":
          "The date that the terms of service provided at terms_url were last updated (added in v2.3-RC)",
          "type": "string",
          "format": "date"
        },
        "privacy_url": {
          "description":
          "A fully qualified URL pointing to the privacy policy for the service (added in v2.3-RC).",
          "type": "string",
          "format": "uri"
        },
        "privacy_last_updated": {
          "description":
          "The date that the privacy policy provided at privacy_url was last updated (added in v2.3-RC).",
          "type": "string",
          "format": "date"
        },
        "rental_apps": {
          "description":
            "Contains rental app information in the android and ios JSON objects (added in v1.1).",
          "type": "object",
          "properties": {
            "android": {
              "description":
                "Contains rental app download and app discovery information for the Android platform. (added in v1.1)",
              "type": "object",
              "properties": {
                "store_uri": {
                  "description":
                    "URI where the rental Android app can be downloaded from (added in v1.1).",
                  "type": "string",
                  "format": "uri"
                },
                "discovery_uri": {
                  "description":
                    "URI that can be used to discover if the rental Android app is installed on the device (added in v1.1).",
                  "type": "string",
                  "format": "uri"
                }
              },
              "required": ["store_uri", "discovery_uri"]
            },
            "ios": {
              "description":
                "Contains rental information for the iOS platform (added in v1.1).",
              "type": "object",
              "properties": {
                "store_uri": {
                  "description":
                    "URI where the rental iOS app can be downloaded from (added in v1.1).",
                  "type": "string",
                  "format": "uri"
                },
                "discovery_uri": {
                  "description":
                    "URI that can be used to discover if the rental iOS app is installed on the device (added in v1.1).",
                  "type": "string",
                  "format": "uri"
                }
              },
              "required": ["store_uri", "discovery_uri"]
            }
          }
        }
      },
      "required": ["system_id", "language", "name", "timezone"],
      "dependentRequired": {
        "terms_url": ["terms_last_updated"],
        "privacy_url": ["privacy_last_updated"]
      }
    }
  },
  "required": ["last_updated", "ttl", "version", "data"]
}

=== MobilityData/gbfs-json-schema/testFixtures/v2.3/system_information.json
{
  "last_updated": 1640887163,
  "ttl": 1800,
  "version": "2.3",
  "data": {
    "system_id": "example_cityname",
    "language": "en",
    "name": "Example Bike Rental",
    "short_name": "Example Bike",
    "operator": "Example Sharing, Inc",
    "url": "https://www.example.com",
    "purchase_url": "https://www.example.com",
    "start_date": "2010-06-10",
    "phone_number": "1-800-555-1234",
    "email": "customerservice@example.com",
    "feed_contact_email": "datafeed@example.com",
    "timezone": "America/Chicago",
    "license_url": "https://www.example.com/data-license.html",
    "terms_url": "https://www.example.com/terms",
    "terms_last_updated": "2021-06-21",
    "privacy_url": "https://www.example.com/privacy-policy",
    "privacy_last_updated": "2019-01-13",
    "rental_apps": {
      "android": {
        "discovery_uri": "com.example.android://",
        "store_uri": "https://play.google.com/store/apps/details?id=com.example.android"
      },
      "ios": {
        "store_uri": "https://apps.apple.com/app/apple-store/id123456789",
        "discovery_uri": "com.example.ios://"
      }
    },
    "brand_assets": {
        "brand_last_modified": "2021-06-15",
        "brand_image_url": "https://www.example.com/assets/brand_image.svg",
        "brand_image_url_dark": "https://www.example.com/assets/brand_image_dark.svg",
        "color": "#C2D32C",
        "brand_terms_url": "https://www.example.com/assets/brand.pdf"
      }
      
  }
}
