=== MobilityData/gbfs-json-schema/src/main/resources/schema/free_bike_status/free_bike_status.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://github.com/NABSA/gbfs/blob/master/gbfs.md#free_bike_statusjson",
  "description": "Describes the vehicles that are available for rent (as of v2.1-RC2).",
  "type": "object",
  "properties": {
    "last_updated": {
      "description": "Last time the data in the feed was updated in POSIX time.",
      "type": "integer",
      "minimum": 1450155600
    },
    "ttl": {
      "description": "Number of seconds before the data in the feed will be updated again (0 if the data should always be refreshed).",
      "type": "integer",
      "minimum": 0
    },
    "version": {
      "description": "GBFS version number to which the feed conforms, according to the versioning framework (added in v1.1).",
      "type": "string",
      "enum": [
        "2.2",
        "3.0-RC",
        "3.0"
      ]
    },
    "data": {
      "description": "Array that contains one object per bike as defined below.",
      "type": "object",
      "properties": {
        "bikes": {
          "type": "array",
          "items": {
            "type":"object",
            "properties": {
              "bike_id": {
                "description": "Rotating (as of v2.0) identifier of a vehicle.",
                "type": "string"
              },
              "lat": {
                "description": "The latitude of the vehicle.",
                "type": "number",
                "minimum": -90,
                "maximum": 90
              },
              "lon": {
                "description": "The longitude of the vehicle.",
                "type": "number",
                "minimum": -180,
                "maximum": 180
              },
              "is_reserved": {
                "description": "Is the vehicle currently reserved?",
                "type": "boolean"
              },
              "is_disabled": {
                "description": "Is the vehicle currently disabled (broken)?",
                "type": "boolean"
              },
              "rental_uris": {
                "description": "Contains rental uris for Android, iOS, and web in the android, ios, and web fields (added in v1.1).",
                "type": "object",
                "properties": {
                  "android": {
                    "description": "URI that can be passed to an Android app with an intent (added in v1.1).",
                    "type": "string",
                    "format": "uri"
                  },
                  "ios": {
                    "description": "URI that can be used on iOS to launch the rental app for this vehicle (added in v1.1).",
                    "type": "string",
                    "format": "uri"
                  },
                  "web": {
                    "description": "URL that can be used by a web browser to show more information about renting this vehicle (added in v1.1).",
                    "type": "string",
                    "format": "uri"
                  }
                }
              },
              "vehicle_type_id": {
                "description": "The vehicle_type_id of this vehicle (added in v2.1-RC).",
                "type": "string"
              },
              "last_reported": {
                "description": "The last time this vehicle reported its status to the operator's backend in POSIX time (added in v2.1-RC).",
                "type": "number",
                "minimum": 1450155600
              },
              "current_range_meters": {
                "description": "The furthest distance in meters that the vehicle can travel without recharging or refueling with the vehicle's current charge or fuel (added in v2.1-RC).",
                "type": "number",
                "minimum": 0
              },
              "station_id": {
                "description": "Identifier referencing the station_id if the vehicle is currently at a station (added in v2.1-RC2).",
                "type": "string"
              },
              "pricing_plan_id": {
                "description": "The plan_id of the pricing plan this vehicle is eligible for (added in v2.1-RC2).",
                "type": "string"
              }
            },
            "required": [
              "bike_id",
              "is_reserved",
              "is_disabled"
            ]     
          },
          "required": [
            "bikes"
          ]
        }
      }
    }
  },
  "required": [
    "last_updated",
    "ttl",
    "version",
    "data"
  ]
}

=== MobilityData/gbfs-json-schema/gbfs-java-model/src/test/resources/v3_0/system_alerts.json
{
  "last_updated": 1604519393,
  "ttl": 60,
  "version": "3.0",
  "data": {
    "alerts": [
      {
        "alert_id": "21",
        "type": "station_closure",
        "station_ids": [
          "123",
          "456",
          "789"
        ],
        "times": [
          {
            "start": 1604448000,
            "end": 1604674800
          }
        ],
        "url": [
          {
            "text": "https://example.com/more-info",
            "language": "en"
          }
        ],
        "summary": [
          {
            "text": "Disruption of Service",
            "language": "en"
          }
        ],
        "description": [
          {
            "text": "The three stations on Broadway will be out of service from 12:00am Nov 3 to 3:00pm Nov 6th to accommodate road work",
            "language": "en"
          }
        ],
        "last_updated": 1604198100
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/models/java/gbfs-java-model/src/test/resources/v3_0/geofencing_zones.json
{
  "last_updated": 1640887163,
  "ttl": 60,
  "version": "3.0",
  "data": {
    "geofencing_zones": {
      "type": "FeatureCollection",
      "features": [
        {
          "type": "Feature",
          "geometry": {
            "type": "MultiPolygon",
            "coordinates": [
              [
                [
                  [
                    -122.578067,
                    45.562982
                  ],
                  [
                    -122.661838,
                    45.562741
                  ],
                  [
                    -122.661151,
                    45.504542
                  ],
                  [
                    -122.578926,
                    45.5046625
                  ],
                  [
                    -122.578067,
                    45.562982
                  ]
                ]
              ],
              [
                [
                  [
                    -122.650680,
                    45.548197
                  ],
                  [
                    -122.650852,
                    45.534731
                  ],
                  [
                    -122.630939,
                    45.535212
                  ],
                  [
                    -122.630424,
                    45.548197
                  ],
                  [
                    -122.650680,
                    45.548197
                  ]
                ]
              ]
            ]
          },
          "properties": {
            "name": [
              {
                "text": "NE 24th/NE Knott",
                "language": "en"
              }
            ],
            "start": 1593878400,
            "end": 1593907260,
            "rules": [
              {
                "vehicle_type_id": [
                  "moped1",
                  "car1"
                ],
                "ride_start_allowed": false,
                "ride_end_allowed": false,
                "ride_through_allowed": true,
                "maximum_speed_kph": 10,
                "station_parking": true
              }
            ]
          }
        }
      ]
    },
    "global_rules": [
      {
        "ride_start_allowed": false,
        "ride_end_allowed": false,
        "ride_through_allowed": true
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/gbfs-java-model/src/test/resources/v3_0_RC/system_pricing_plans.json
{
  "last_updated": 1640887163,
  "ttl": 0,
  "version": "3.0-RC",
  "data": {
    "plans": [
      {
        "plan_id": "plan2",
        "name": [
          {
            "text": "One-Way",
            "language": "en"
          }
        ],
        "currency": "USD",
        "price": 2.00,
        "reservation_price_per_min": 0.15,
        "is_taxable": false,
        "description": [
          {
            "text": "Includes 10km, overage fees apply after 10km.",
            "language": "en"
          }
        ],
        "per_km_pricing": [
          {
            "start": 10,
            "rate": 1.00,
            "interval": 1,
            "end": 25
          },
          {
            "start": 25,
            "rate": 0.50,
            "interval": 1
          },
          {
            "start": 25,
            "rate": 3.00,
            "interval": 5
          }
        ]
      },
      {
        "plan_id": "plan3",
        "name": [
          {
            "text": "Simple Rate",
            "language": "en"
          }
        ],
        "currency": "CAD",
        "price": 3.00,
        "is_taxable": true,
        "description": [
          {
            "text": "$3 unlock fee, $0.25 per kilometer and 0.50 per minute.",
            "language": "en"
          }
        ],
        "per_km_pricing": [
          {
            "start": 0,
            "rate": 0.25,
            "interval": 1
          }
        ],
        "per_min_pricing": [
          {
            "start": 0,
            "rate": 0.50,
            "interval": 1
          }
        ]
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/src/test/resources/v3_0_RC/vehicle_types.json
{
  "last_updated": 1640887163,
  "ttl": 0,
  "version": "3.0-RC",
  "data": {
    "vehicle_types": [
      {
        "vehicle_type_id": "abc123",
        "form_factor": "bicycle",
        "propulsion_type": "human",
        "name": [
          {
            "text": "Example Basic Bike",
            "language": "en"
          }
        ],
        "wheel_count": 2,
        "default_reserve_time": 30,
        "return_constraint": "any_station",
        "vehicle_assets": {
          "icon_url": "https://www.example.com/assets/icon_bicycle.svg",
          "icon_url_dark": "https://www.example.com/assets/icon_bicycle_dark.svg",
          "icon_last_modified": "2021-06-15"
        },
        "default_pricing_plan_id": "bike_plan_1",
        "pricing_plan_ids": [
          "bike_plan_1",
          "bike_plan_2",
          "bike_plan_3"
        ]
      },
      {
        "vehicle_type_id": "cargo123",
        "form_factor": "cargo_bicycle",
        "propulsion_type": "human",
        "name": [
          {
            "text": "Example Cargo Bike",
            "language": "en"
          }
        ],
        "description": [
          {
            "text": "Extra comfortable seat with additional suspension.\n\nPlease be aware of the cargo box lock: you need to press it down before pulling it up again!",
            "language": "en"
          }
        ],
        "wheel_count": 3,
        "default_reserve_time": 30,
        "return_constraint": "roundtrip_station",
        "vehicle_assets": {
          "icon_url": "https://www.example.com/assets/icon_cargobicycle.svg",
          "icon_url_dark": "https://www.example.com/assets/icon_cargobicycle_dark.svg",
          "icon_last_modified": "2021-06-15"
        },
        "default_pricing_plan_id": "cargo_plan_1",
        "pricing_plans_ids": [
          "cargo_plan_1",
          "cargo_plan_2",
          "cargo_plan_3"
        ]
      },
      {
        "vehicle_type_id": "def456",
        "form_factor": "scooter_standing",
        "propulsion_type": "electric",
        "name": [
          {
            "text": "Example E-scooter V2",
            "language": "en"
          }
        ],
        "wheel_count": 2,
        "max_permitted_speed": 25,
        "rated_power": 350,
        "default_reserve_time": 30,
        "max_range_meters": 12345,
        "return_constraint": "free_floating",
        "vehicle_assets": {
          "icon_url": "https://www.example.com/assets/icon_escooter.svg",
          "icon_url_dark": "https://www.example.com/assets/icon_escooter_dark.svg",
          "icon_last_modified": "2021-06-15"
        },
        "default_pricing_plan_id": "scooter_plan_1"
      },
      {
        "vehicle_type_id": "car1",
        "form_factor": "car",
        "rider_capacity": 5,
        "cargo_volume_capacity": 200,
        "propulsion_type": "combustion_diesel",
        "eco_label": [
          {
            "country_code": "FR",
            "eco_sticker": "critair_1"
          },
          {
            "country_code": "DE",
            "eco_sticker": "euro_2"
          }
        ],
        "name": [
          {
            "text": "Four-door Sedan",
            "language": "en"
          }
        ],
        "wheel_count": 4,
        "default_reserve_time": 0,
        "max_range_meters": 523992,
        "return_constraint": "roundtrip_station",
        "vehicle_accessories": [
          "doors_4",
          "automatic",
          "cruise_control"
        ],
        "g_CO2_km": 120,
        "vehicle_image": "https://www.example.com/assets/renault-clio.jpg",
        "make": [
          {
            "text": "Renault",
            "language": "en"
          }
        ],
        "model": [
          {
            "text": "Clio",
            "language": "en"
          }
        ],
        "color": "white",
        "vehicle_assets": {
          "icon_url": "https://www.example.com/assets/icon_car.svg",
          "icon_url_dark": "https://www.example.com/assets/icon_car_dark.svg",
          "icon_last_modified": "2021-06-15"
        },
        "default_pricing_plan_id": "car_plan_1"
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/models/java/gbfs-java-model/src/test/resources/v3_0/system_regions.json
{
  "last_updated": 1640887163,
  "ttl": 86400,
  "version": "3.0",
  "data": {
    "regions": [
      {
        "name": [
          {
            "text": "North",
            "language": "en"
          }
        ],
        "region_id": "3"
      },
      {
        "name": [
          {
            "text": "East",
            "language": "en"
          }
        ],
        "region_id": "4"
      },
      {
        "name": [
          {
            "text": "South",
            "language": "en"
          }
        ],
        "region_id": "5"
      },
      {
        "name": [
          {
            "text": "West",
            "language": "en"
          }
        ],
        "region_id": "6"
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/gbfs-java-model/src/test/resources/v3_0_RC/system_information.json
{
  "last_updated": 1640887163,
  "ttl": 1800,
  "version": "3.0-RC",
  "data": {
    "system_id": "example_cityname",
    "languages": ["en"],
    "name": [
      {
        "text": "Example Bike Rental",
        "language": "en"
      }
    ],
    "short_name": [
      {
        "text": "Example Bike",
        "language": "en"
      }
    ],
    "operator": [
      {
        "text": "Example Sharing, Inc",
        "language": "en"
      }
    ],
    "opening_hours": "Apr 1-Nov 3 00:00-24:00",
    "start_date": "2010-06-10",
    "url": "https://www.example.com",
    "purchase_url": "https://www.example.com",
    "phone_number": "+18005551234",
    "email": "customerservice@example.com",
    "feed_contact_email": "datafeed@example.com",
    "timezone": "America/Chicago",
    "license_url": "https://www.example.com/data-license.html",
    "terms_url": [
      {
        "text": "https://www.example.com/en/terms",
        "language": "en"
      }
    ],
    "terms_last_updated": "2021-06-21",
    "privacy_url": [
      {
        "text": "https://www.example.com/en/privacy-policy",
        "language": "en"
      }
    ],
    "privacy_last_updated": "2019-01-13",
    "rental_apps": {
      "android": {
        "discovery_uri": "com.example.android://",
        "store_uri": "https://play.google.com/store/apps/details?id=com.example.android"
      },
      "ios": {
        "store_uri": "https://apps.apple.com/app/apple-store/id123456789",
        "discovery_uri": "com.example.ios://"
      }
    },
    "brand_assets": {
      "brand_last_modified": "2021-06-15",
      "brand_image_url": "https://www.example.com/assets/brand_image.svg",
      "brand_image_url_dark": "https://www.example.com/assets/brand_image_dark.svg",
      "color": "#C2D32C",
      "brand_terms_url": "https://www.example.com/assets/brand.pdf"
    }

  }
}

=== MobilityData/gbfs-json-schema/gbfs-java-model/src/test/resources/v2_X/system_pricing_plans.json
{
  "last_updated": 1606858558,
  "ttl": 300,
  "version": "2.2",
  "data": {
    "plans": [
      {
        "plan_id": "TST:PricingPlan:Basic",
        "name": "Basic",
        "currency": "NOK",
        "price": 0.0,
        "is_taxable": false,
        "description": "Start NOK 0, Per minute 3,50 NOK",
        "per_min_pricing": [
          {
            "start": 0,
            "rate": 3.5,
            "interval": 1
          }
        ]
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/src/test/resources/system_information.json
{
  "last_updated": 1606830357,
  "ttl": 300,
  "version": "2.2",
  "data": {
    "system_id": "TST:System:Test",
    "language": "en",
    "name": "Test",
    "url": "https://www.test.com/",
    "timezone": "Europe/Oslo",
    "rental_apps": {
      "android": {
        "store_uri": "https://play.google.com/store/apps/details?id=com.testrental.android",
        "discovery_uri": "com.testrental.android://"
      },
      "ios": {
        "store_uri": "https://apps.apple.com/app/apple-store/id123456789",
        "discovery_uri": "com.testrental.ios://"
      }
    }
  }
}
