=== MobilityData/gbfs-json-schema/src/main/resources/schema/free_bike_status/free_bike_status.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://github.com/NABSA/gbfs/blob/master/gbfs.md#free_bike_statusjson",
  "description": "Describes the vehicles that are available for rent (as of v2.1-RC2).",
  "type": "object",
  "properties": {
    "last_updated": {
      "description": "Last time the data in the feed was updated in POSIX time.",
      "type": "integer",
      "minimum": 1450155600
    },
    "ttl": {
      "description": "Number of seconds before the data in the feed will be updated again (0 if the data should always be refreshed).",
      "type": "integer",
      "minimum": 0
    },
    "version": {
      "description": "GBFS version number to which the feed conforms, according to the versioning framework (added in v1.1).",
      "type": "string",
      "enum": [
        "2.2",
        "3.0-RC",
        "3.0"
      ]
    },
    "data": {
      "description": "Array that contains one object per bike as defined below.",
      "type": "object",
      "properties": {
        "bikes": {
          "type": "array",
          "items": {
            "type":"object",
            "properties": {
              "bike_id": {
                "description": "Rotating (as of v2.0) identifier of a vehicle.",
                "type": "string"
              },
              "lat": {
                "description": "The latitude of the vehicle.",
                "type": "number",
                "minimum": -90,
                "maximum": 90
              },
              "lon": {
                "description": "The longitude of the vehicle.",
                "type": "number",
                "minimum": -180,
                "maximum": 180
              },
              "is_reserved": {
                "description": "Is the vehicle currently reserved?",
                "type": "boolean"
              },
              "is_disabled": {
                "description": "Is the vehicle currently disabled (broken)?",
                "type": "boolean"
              },
              "rental_uris": {
                "description": "Contains rental uris for Android, iOS, and web in the android, ios, and web fields (added in v1.1).",
                "type": "object",
                "properties": {
                  "android": {
                    "description": "URI that can be passed to an Android app with an intent (added in v1.1).",
                    "type": "string",
                    "format": "uri"
                  },
                  "ios": {
                    "description": "URI that can be used on iOS to launch the rental app for this vehicle (added in v1.1).",
                    "type": "string",
                    "format": "uri"
                  },
                  "web": {
                    "description": "URL that can be used by a web browser to show more information about renting this vehicle (added in v1.1).",
                    "type": "string",
                    "format": "uri"
                  }
                }
              },
              "vehicle_type_id": {
                "description": "The vehicle_type_id of this vehicle (added in v2.1-RC).",
                "type": "string"
              },
              "last_reported": {
                "description": "The last time this vehicle reported its status to the operator's backend in POSIX time (added in v2.1-RC).",
                "type": "number",
                "minimum": 1450155600
              },
              "current_range_meters": {
                "description": "The furthest distance in meters that the vehicle can travel without recharging or refueling with the vehicle's current charge or fuel (added in v2.1-RC).",
                "type": "number",
                "minimum": 0
              },
              "station_id": {
                "description": "Identifier referencing the station_id if the vehicle is currently at a station (added in v2.1-RC2).",
                "type": "string"
              },
              "pricing_plan_id": {
                "description": "The plan_id of the pricing plan this vehicle is eligible for (added in v2.1-RC2).",
                "type": "string"
              }
            },
            "required": [
              "bike_id",
              "is_reserved",
              "is_disabled"
            ]     
          },
          "required": [
            "bikes"
          ]
        }
      }
    }
  },
  "required": [
    "last_updated",
    "ttl",
    "version",
    "data"
  ]
}

=== MobilityData/gbfs-json-schema/src/test/resources/station_information.json
{
  "last_updated": 1434054678,
  "ttl": 0,
  "version": "2.2",
  "data": {
    "stations": [
      {
        "station_id": "TST:Station:1",
        "name": "Cool bikes",
        "lat": 12.34,
        "lon": 45.67,
        "vehicle_type_capacity": {
          "TST:VehicleType:CityBike": 7
        }
      },
      {
        "station_id": "TST:Station:2",
        "name": "Cooler bikes",
        "lat": 11.34,
        "lon": 44.67,
        "vehicle_type_capacity": {
          "TST:VehicleType:CityBike": 12
        }
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/src/test/resources/v3_0_RC/vehicle_status.json
{
  "last_updated":1640887163,
  "ttl":0,
  "version":"3.0-RC",
  "data":{
    "vehicles":[
      {
        "vehicle_id":"973a5c94-c288-4a2b-afa6-de8aeb6ae2e5",
        "last_reported":1609866109,
        "lat":12.345678,
        "lon":56.789012,
        "is_reserved":false,
        "is_disabled":false,
        "vehicle_type_id":"abc123",
        "rental_uris": {
          "android": "https://www.example.com/app?vehicle_id=973a5c94-c288-4a2b-afa6-de8aeb6ae2e5&platform=android&",
          "ios": "https://www.example.com/app?vehicle_id=973a5c94-c288-4a2b-afa6-de8aeb6ae2e5&platform=ios"
        }
      },
      {
        "vehicle_id":"987fd100-b822-4347-86a4-b3eef8ca8b53",
        "last_reported":1609866204,
        "is_reserved":false,
        "is_disabled":false,
        "vehicle_type_id":"def456",
        "current_range_meters":6543.0,
        "station_id":"86",
        "pricing_plan_id":"plan3"
      },
      {
        "vehicle_id":"45bd3fb7-a2d5-4def-9de1-c645844ba962",
        "last_reported":1609866109,
        "lat":12.345678,
        "lon":56.789012,
        "is_reserved":false,
        "is_disabled":false,
        "vehicle_type_id":"abc123",
        "current_range_meters":400000.0,
        "available_until":"2021-05-17T15:00:00Z",
        "home_station_id":"station1",
        "vehicle_equipment":[
          "child_seat_a",
          "winter_tires"
        ]
      },
      {
        "vehicle_id":"d4521def-7922-4e46-8e1d-8ac397239bd0",
        "last_reported":1609866204,
        "is_reserved":false,
        "is_disabled":false,
        "vehicle_type_id":"def456",
        "current_fuel_percent":0.7,
        "current_range_meters":6543.0,
        "station_id":"86",
        "pricing_plan_id":"plan3",
        "home_station_id":"146",
        "vehicle_equipment":[
          "child_seat_a"
        ]
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/models/java/gbfs-java-model/src/test/resources/v2_X/station_status.json
{
  "last_updated": 1434054678,
  "ttl": 0,
  "version": "2.2",
  "data": {
    "stations": [
      {
        "station_id": "TST:Station:1",
        "is_installed": true,
        "is_renting": true,
        "is_returning": true,
        "last_reported": 1434054678,
        "num_docks_available": 3,
        "vehicle_docks_available": [{
          "vehicle_type_ids": ["TST:VehicleType:Scooter"],
          "count": 2
        }, {
          "vehicle_type_ids": ["TST:VehicleType:CityBike"],
          "count": 1
        }],
        "num_bikes_available": 1,
        "vehicle_types_available": [{
          "vehicle_type_id": "TST:VehicleType:Scooter",
          "count": 1
        }, {
          "vehicle_type_id": "TST:VehicleType:CityBike",
          "count": 0
        }]
      }, {
        "station_id": "TST:Station:2",
        "is_installed": true,
        "is_renting": true,
        "is_returning": true,
        "last_reported": 1434054678,
        "num_docks_available": 8,
        "vehicle_docks_available": [{
          "vehicle_type_ids": ["TST:VehicleType:Scooter"],
          "count": 6
        }, {
          "vehicle_type_ids": ["TST:VehicleType:CityBike"],
          "count": 2
        }],
        "num_bikes_available": 6,
        "vehicle_types_available": [{
          "vehicle_type_id": "TST:VehicleType:Scooter",
          "count": 2
        }, {
          "vehicle_type_id": "TST:VehicleType:CityBike",
          "count": 4
        }]
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/src/test/resources/v2_X/system_alerts.json
{
  "last_updated": 1434054678,
  "ttl": 0,
  "version": "2.2",
  "data": {
    "alerts": [
      {
        "alert_id": "TST:Alert:1",
        "type": "station_closure",
        "times": [
          {
            "start": 1434054678,
            "end": 1434054987
          }
        ],
        "station_ids": ["TST:Station:1"],
        "summary": "Closed for maintenance",
        "description": "Station is closed to install more docks.",
        "last_updated": 1434054678
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/models/java/gbfs-java-model/src/test/resources/v2_X/gbfs.json
{
  "last_updated": 1606727710,
  "ttl": 300,
  "version": "2.2",
  "data": {
    "en": {
      "feeds": [
        {
          "name": "gbfs_versions",
          "url": "https://test.com/gbfs_versions"
        },
        {
          "name": "system_information",
          "url": "https://test.com/system_information"
        },
        {
          "name": "vehicle_types",
          "url": "https://test.com/vehicle_types"
        },
        {
          "name": "station_information",
          "url": "https://test.com/station_information"
        },
        {
          "name": "station_status",
          "url": "https://test.com/station_status"
        },
        {
          "name": "free_bike_status",
          "url": "https://test.com/free_bike_status"
        },
        {
          "name": "system_regions",
          "url": "https://test.com/system_regions"
        },
        {
          "name": "system_pricing_plans",
          "url": "https://test.com/system_pricing_plans"
        },
        {
          "name": "system_hours",
          "url": "https://test.com/system_hours"
        },
        {
          "name": "system_calendar",
          "url": "https://test.com/system_calendar"
        },
        {
          "name": "system_alerts",
          "url": "https://test.com/system_alerts"
        },
        {
          "name": "geofencing_zones",
          "url": "https://test.com/geofencing_zones"
        }
      ]
    }
  }
}

=== MobilityData/gbfs-json-schema/src/test/resources/v2_X/system_hours.json
{
  "last_updated": 1434054678,
  "ttl": 0,
  "version": "2.2",
  "data": {
    "rental_hours": [
      {
        "user_types": [ "member" ],
        "days": ["sat", "sun"],
        "start_time": "00:00:00",
        "end_time": "23:59:59"
      },
      {
        "user_types": [ "nonmember" ],
        "days": ["sat", "sun"],
        "start_time": "05:00:00",
        "end_time": "23:59:59"
      },
      {
        "user_types": [ "member", "nonmember" ],
        "days": ["mon", "tue", "wed", "thu", "fri"],
        "start_time": "00:00:00",
        "end_time": "23:59:59"
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/src/test/resources/v2_X/free_bike_status.json
{
  "last_updated": 1606857968,
  "ttl": 300,
  "version": "2.2",
  "data": {
    "bikes": [
      {
        "bike_id": "TST:Scooter:1234",
        "lat": 59.91465759277344,
        "lon": 10.760470390319824,
        "is_reserved": false,
        "is_disabled": true,
        "vehicle_type_id": "TST:VehicleType:Scooter",
        "current_range_meters": 1431.2,
        "pricing_plan_id": "TST:PricingPlan:Basic",
        "rental_uris": {
          "android": "test://rentme/TST:Scooter:1234",
          "ios": "test://rentme/TST:Scooter:1234",
          "web": "https://test.com/rentme/TST:Scooter:1234"
        }
      }
    ]
  }
}

=== MobilityData/gbfs-json-schema/gbfs-java-model/src/test/resources/v3_0_RC/gbfs_versions.json
{
  "last_updated": 1640887163,
  "ttl": 0,
  "version": "3.0-RC",
  "data": {
    "versions": [
      {
        "version": "2.0",
        "url": "https://www.example.com/gbfs/2/gbfs"
      },
      {
        "version": "3.0-RC",
        "url": "https://www.example.com/gbfs/3/gbfs"
      }
    ]
  }
}
